# Generated by Django 2.0.3 on 2018-06-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
