# Generated by Django 2.0.3 on 2018-06-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('manager', models.CharField(max_length=256, null=True)),
                ('title', models.CharField(max_length=512)),
                ('funding_source', models.CharField(default='', max_length=512, null=True)),
                ('starts_at', models.DateField()),
                ('ends_at', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'circles',
            },
        ),
    ]
