# Generated by Django 2.0.3 on 2018-03-25 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='program',
            name='end_date',
        ),
    ]
