# Generated by Django 2.0.3 on 2018-06-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180611_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='refunded',
        ),
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
