# Generated by Django 2.0.3 on 2018-05-19 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_student_programs'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('student', 'program')},
        ),
    ]
