# Generated by Django 2.0.3 on 2018-06-15 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180614_2008'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Program',
        ),
    ]
