# Generated by Django 2.0.3 on 2018-05-19 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180519_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='programs',
        ),
    ]
