# Generated by Django 2.0.3 on 2018-05-20 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_student_programs'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='full_time',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
