# Generated by Django 2.0.3 on 2018-06-18 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_delete_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='circle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='api.Circle'),
        ),
    ]
