# Generated by Django 2.0.3 on 2018-06-21 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180618_0816'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='circle',
            table='cycles',
        ),
    ]
