# Generated by Django 2.0.3 on 2018-05-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_registration_full_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'expenses',
            },
        ),
        migrations.AddField(
            model_name='program',
            name='expense',
            field=models.ManyToManyField(to='api.Expense'),
        ),
    ]
