# Generated by Django 2.0.3 on 2018-06-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180621_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='id_university',
            field=models.CharField(default='1234', max_length=20),
            preserve_default=False,
        ),
    ]
