# Generated by Django 2.0.3 on 2018-05-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20180527_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=10000000, max_digits=10),
            preserve_default=False,
        ),
    ]
