# Generated by Django 2.0.3 on 2018-06-11 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180611_1739'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='registration',
            name='circle',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='student',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='registration',
        ),
        migrations.AddField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='circle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Circle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='full_time',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
