# Generated by Django 2.0.3 on 2018-06-14 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180613_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='tuition',
            field=models.DecimalField(decimal_places=2, default=2800, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='budget_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='api.BudgetField'),
        ),
    ]
