# Generated by Django 2.0.3 on 2018-06-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_student_id_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id_university',
            field=models.CharField(default='', max_length=20),
        ),
    ]
