# Generated by Django 2.0.3 on 2018-06-23 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20180621_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='notes',
            field=models.CharField(default='', max_length=512),
        ),
    ]
