# Generated by Django 2.0.3 on 2018-06-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20180623_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='notes',
            field=models.CharField(default='', max_length=512, null=True),
        ),
    ]
