# Generated by Django 2.0.3 on 2018-06-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20180624_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
