"""empty message

Revision ID: 032a028eff5b
Revises: 
Create Date: 2017-04-23 01:15:15.067333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '032a028eff5b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['email'], ['google_users.email'], ),
    sa.PrimaryKeyConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
