"""empty message

Revision ID: ad98c9bb71c8
Revises: ff9647105cfd
Create Date: 2017-04-16 17:41:37.911255

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ad98c9bb71c8'
down_revision = 'ff9647105cfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token', sa.String(length=256), nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', mysql.VARCHAR(length=32), nullable=True))
    op.drop_column('users', 'token')
    # ### end Alembic commands ###
