"""empty message

Revision ID: c709c3e5fd2f
Revises: 032a028eff5b
Create Date: 2017-04-23 01:17:39.032166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c709c3e5fd2f'
down_revision = '032a028eff5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'google_users', 'users', ['email'], ['email'])
    op.drop_constraint('users_ibfk_1', 'users', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('users_ibfk_1', 'users', 'google_users', ['email'], ['email'])
    op.drop_constraint(None, 'google_users', type_='foreignkey')
    # ### end Alembic commands ###
